/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as AuthenticatedImport } from './../routes/_authenticated'
import { Route as AnonymousImport } from './../routes/_anonymous'

// Create Virtual Routes

const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const AnonymousLoginLazyImport = createFileRoute('/_anonymous/login')()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AnonymousRoute = AnonymousImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./../routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AnonymousLoginLazyRoute = AnonymousLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => AnonymousRoute,
} as any).lazy(() =>
  import('./../routes/_anonymous/login.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonymousImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_anonymous/login': {
      id: '/_anonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AnonymousLoginLazyImport
      parentRoute: typeof AnonymousImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AnonymousRoute: AnonymousRoute.addChildren({ AnonymousLoginLazyRoute }),
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_anonymous",
        "/_authenticated"
      ]
    },
    "/_anonymous": {
      "filePath": "_anonymous.tsx",
      "children": [
        "/_anonymous/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/"
      ]
    },
    "/_anonymous/login": {
      "filePath": "_anonymous/login.lazy.tsx",
      "parent": "/_anonymous"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
